  version: '3'
  services:
    db-users:
      container_name: db-users
      image: mysql:latest
      restart: unless-stopped
      environment:
        MYSQL_DATABASE: ms_registrations
        MYSQL_USER: user
        MYSQL_PASSWORD: Test123
        MYSQL_ROOT_PASSWORD: root
      ports:
        - 3306:3306
      expose:
        - 3306
      networks:
        - microservices-network
    ms-registrations:
     container_name: container_registrations
     image: img/ms-reistration
     ports: 
      - "8080:8080"
     depends_on:
         - db-users
     networks:
       - microservices-network

       ### Zookeeper
    ms-notifications:
      container_name: container_notifications
      image: img/ms-notification
      ports:
        - "8081:8081"
      networks:
        - microservices-network
    zookeeper:
      container_name: zookeeper
      image: confluentinc/cp-zookeeper:7.4.0
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000
      networks:
        - microservices-network
    kafka:
     container_name: kafka
     image: confluentinc/cp-kafka:7.4.0
     depends_on:
      - zookeeper
     ports:
      - "9092:9092"
     environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
     networks:
       - microservices-network


  networks:
    microservices-network:
